version: "3"
services:
  telrobot:
#    build: ../..
    image: telrobot:v1.0
    container_name: telrobot
    ports:
      - "4000:4000"
    restart: always
#    network_mode: "host"
    logging:
      options:
        max-size: "1g"
        max-file: "2"
    depends_on:
      - postgres
    environment:
      - GIN_MODE=release
      - OC_DB_URL=host=postgres port=5432 user=robot password=robot dbname=robot sslmode=disable
      - TOKEN=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjUxOWVmMmI0NTIwZDJhMzU3ZDNmZTdkZjE1Y2RmOGQ3NDJmOGNjNGViODVlNWI1ZWRmYjcyYjYyODg2NDU2NmYwOWFiZjM2OGRkNjViYjYwIn0.eyJhdWQiOiIxIiwianRpIjoiNTE5ZWYyYjQ1MjBkMmEzNTdkM2ZlN2RmMTVjZGY4ZDc0MmY4Y2M0ZWI4NWU1YjVlZGZiNzJiNjI4ODY0NTY2ZjA5YWJmMzY4ZGQ2NWJiNjAiLCJpYXQiOjE2NTM3MDE2ODQsIm5iZiI6MTY1MzcwMTY4NCwiZXhwIjoxNjg1MjM3Njg0LCJzdWIiOiJiNzM0NTYyMy0xMGRjLTRjNjktOGFhNy1jODdmMThmODljMzciLCJzY29wZXMiOltdfQ.cLqXS2KEOEvfdYOGFMeCqtphHb_JLubwjI1oKYxFgS0bIeMRolTSSWi1BE0HWO5DRmGAxrDOBS4iGqWtsb1FdUhbQnLYIe1aa9jOwGHm6kR_GJHHF3ETai8UGWqaTjnuiC74IsexyIlgr3Qj7w4kDuJuO60SnYcJTrxsIRRh736P71tux61PZrokM9UjAFqrD9Pn7kIHcsCuMGdExQm8MmFkDGC9VIMgfWrdtEAyZd-eEhTpqLlyA-ov_LCQeFiZHhfm18zWH_KFmvYj1ftqv_o8mQ5GcF8Q_43umiPZXH70rEaQutp79KNmt0g08_-Y3TwG2PY57P9WB0_boeRAeycoCWwUk_F0CmulM0eyBs-OIyI6HIxXQOQ2O53OYrPglGhoBklVa6Y7_ie3n94xu_I2x1QiDk6Uf_0NqH2V8CIUu_i1v-e-vQmYWAL_K9TGDOPBiq_J2soyuA7qHfd1kswF2O2nYQdJ6TlS2Fe-WYtN1PiJ3M9UPgKGm8JHekib-XONmhBCl8cdEhV0SXNPFhXx49CgD65CT8tVDB5VRYPWqPLztoRdkZ5LmrTv2XbpNSMBwT4CwXhaeLMPKxtl2HHTHmvPYMCZGaib3TAPdkXkpHKLAMNb91XMu9u8lz1Fq5PRlx5GssCdU_GpOCgww7gyWatFgvzArvaJf_dg60k
  debug-proxy:
    image: alpine/socat
    depends_on:
      - postgres
    ports:
      - "5433:5432"
    entrypoint: /bin/sh
      - ./debug-proxy.sh:/debug-proxy.sh
    command: /debug-proxy.sh

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=robot
      - POSTGRES_USER=robot
      - POSTGRES_PASSWORD=robot
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

#  mysql:
#    container_name: telrobot-mysql
#    restart: always
#    image: mysql:5.7
#    ports:
#      - 3307:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=robot
#    volumes:
#      - ./mysql/conf:/etc/mysql/conf.d
#      - ./mysql/data:/var/lib/mysql